name: scgpt
type: neural_network

pretrained:
  path: models/scgpt/whole-human
  vocab: models/scgpt/whole-human/vocab.json
  weights: models/scgpt/whole-human/best_model.pt

architecture:
  layer_size: 128
  n_layers: 4
  n_heads: 4
  dropout: 0.2
  max_seq_len: 3001
  n_bins: 51
  freeze_encoder: false

training:
  learning_rate: 1e-4
  schedule_ratio: 0.9
  amp: true
  fast_transformer: true

tokenization:
  include_zero_gene: false
  mask_ratio: 0.0