name: scvi
type: integration_and_reference_mapping

# scVI-specific parameters
scvi:
  n_top_genes: 3000
  n_layers: 2
  n_latent: 30
# scANVI-specific parameters
scanvi:
  max_epochs: 20
  n_samples_per_label: 100